### ISSUE TITLE
钉钉同步错误

### ISSUE THREAD

**Issue by xzzgwzh** [ohdarling/virtual-ldap#19]
× dingtalk-provider Dingtalk API error { errcode: 60003, errmsg: '部门不存在' }
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userlist' of null
    at fetchDepartmentUsers (/app/lib/providers/dingtalk.js:181:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fetchAllUsers (/app/lib/providers/dingtalk.js:197:25)
    at async reloadFromDingtalkServer (/app/lib/providers/dingtalk.js:245:20)
    at async Object.setupProvider (/app/lib/providers/dingtalk.js:209:3)
    at async createProvider (/app/lib/utilities/provider.js:13:5)
    at async /app/lib/server.js:240:5
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xzzgwzh** [comment]
钉钉存在家校通讯录，部门ID为-1，就会报错。
