### ISSUE TITLE
验证密码时抱错

### ISSUE THREAD

**Issue by fonolife** [ohdarling/virtual-ldap#5]
The authentication failed
 -  [LDAP result code 49 - invalidCredentials] InvalidCredentialsError
  org.apache.directory.studio.connection.core.io.StudioLdapException:  [LDAP result code 49 - invalidCredentials] InvalidCredentialsError
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.toStudioLdapException(DirectoryApiConnectionWrapper.java:1350)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.access$2(DirectoryApiConnectionWrapper.java:1342)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper$2.run(DirectoryApiConnectionWrapper.java:483)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.runAndMonitor(DirectoryApiConnectionWrapper.java:1261)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.doBind(DirectoryApiConnectionWrapper.java:488)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.bind(DirectoryApiConnectionWrapper.java:323)
	at org.apache.directory.studio.connection.core.jobs.CheckBindRunnable.run(CheckBindRunnable.java:79)
	at org.apache.directory.studio.connection.ui.RunnableContextRunner$1.run(RunnableContextRunner.java:140)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.apache.directory.api.ldap.model.exception.LdapAuthenticationException: InvalidCredentialsError
	at org.apache.directory.api.ldap.model.message.ResultCodeEnum.processResponse(ResultCodeEnum.java:1995)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkResponse(DirectoryApiConnectionWrapper.java:1337)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.access$6(DirectoryApiConnectionWrapper.java:1333)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper$2.run(DirectoryApiConnectionWrapper.java:479)
	... 6 more

   [LDAP result code 49 - invalidCredentials] InvalidCredentialsError

**Comment by ohdarling** [comment]
You should reset user's password from KeyCloak's account page first.
